### PR TITLE
Update javascript.vim

### PR DESCRIPTION
**Pull request by bounceme**
yesterday's commit was still a little buggy, sorry. this should be better

### CODE REVIEW

**Comment by amadeus** [comment]
Hope I'm not a pain, but can you outline what this fixes?

**Comment by bounceme** [comment]
mostly I think my usage of the search pair command was wrong, best to give an example though: 
```
var magicWords = ['abracadabra', 'gesundheit', 'ventrilo'],
  spells = {
    'fireball': function() {
      setOnFire()
    },
    'water': function() {
      putOut()
    }
  },
  a = 1,
  b = 'abc',
  etc, somethingElse
someFunc(param1, param2,
  param3, param4)
```
at the moment this 'inMultiVarIndent' function traverses the curly braces of the spells object. I was close yesterday but for search pair you are generally going to have a few bugs. this is what the indent will look now, you can try with yesterday's and see the difference, basically the rest of the file is broken.

**Comment by bounceme** [comment]
by the way, @amadeus , can class declarations be 'chained' like var statements?

**Comment by amadeus** [comment]
I assume you mean like:

```js
var ClassVar = class {};
```

If so, yes, that is valid JS

**Comment by bounceme** [comment]
no, like multiple class declarations seperated by commas

**Comment by amadeus** [comment]
So like:

```js
class Test1 {}, class Test2 {};
```

If so, no, that is not valid JS, you will get a syntax error on the `,`.

**Comment by bounceme** [comment]
and this?
```
class Test1 {},
Test2 {};
```

**Comment by bounceme** [comment]
chrome dev tools views it as an error at least

**Comment by amadeus** [comment]
Yeah, that's now allowed. Think of a class definition like named functions:

```js
class Durp {};
function Durp(){};
```

**Comment by bounceme** [comment]
this is ready!

**Comment by bounceme** [comment]
any objections?

**Comment by amadeus** [comment]
Can you squash the commits into one commit? Or at least edit the commit messages to be a bit more descriptive? Otherwise, I am good with this.

**Pull request merged**
