### PR TITLE
line following arrow indentation

### PR DESCRIPTION
**Pull request by bounceme**
#332, #330 , #307

### CODE REVIEW

**Comment by bounceme** [comment]
needs #357

**Comment by amadeus** [comment]
Looks good to me!

**Comment by g-sam** [comment]
For me, this solves some of the cases, but not the case where arrow functions are arguments (i.e. the second example raised by @ksmithbaylor in [#332](https://github.com/pangloss/vim-javascript/issues/332)). Same problem on most recent version of develop branch. (Caveat: I am a noob).

**Comment by amadeus** [comment]
@g-sam should be fixed now in `develop`!

**Comment by g-sam** [comment]
Works! Thank you so much!

**Pull request merged**
