### PR TITLE
A fix for #212

### PR DESCRIPTION
**Pull request by amadeus**
As the title states, this is appears to be a very solid indent fix for #212 

I've been using this for the past week and have noticed no negative repercussions yet. And it does seem to fix the issue reported.

### CODE REVIEW

**Comment by davidchambers** [comment]
It's hard to beat a two-character fix!

**Comment by goatslacker** [comment]
:+1:

**Comment by qstrahl** [comment]
Awesome. Nicely done.

**Comment by amadeus** [comment]
All the credit goes to @dragn, as he was the one who figured it out. I was just the guinea pig.

**Pull request merged**
