### PR TITLE
Feature: Block Statement & Label Support

### LINKED ISSUE #687: wrong highlight with ES6 block scope
In such case, highlights and indentations do not work:

``` js
{
  function a() {}
  a();
}
```

image

### PR DESCRIPTION
**Pull request by amadeus**
This is still very rough, and only a first pass. There are some pretty major changes here and so I want to sit on this a bit and test it out. Others can feel free to give this branch a try as well.

I currently have not yet added support for labels, but I want to see if this direction I took has legs to it and doesn't break a bunch of things.

Theoretically, when/if this gets merged, it should fix #687 and #600,

### CODE REVIEW

**Comment by bounceme** [comment]
great, with `let` I think blocks can be somewhat useful now. Labelled blocks are a edge case though

**Comment by amadeus** [comment]
@bounceme I agree, however the label support should be pretty trivial to add, once this in place and not causing any regressions.

**Comment by amadeus** [comment]
Aright, this branch should be ready, minus a bit more testing.

Block statements and labels should be supported.

I just added labels a bit ago, so will sit on it for at least another day to be sure, however the original implementation I had appears to be pretty sound and besides one small ternary issue I found, has been bug free.

**Comment by bounceme** [comment]
edge case:
```
switch(1){
  case 1 ? 2: a:
    i = 'sdfsdf'
}
```
`a` highlights as `jsBlockLabel` instead of `jsSwitchCase`

**Comment by amadeus** [comment]
@bounceme fixed! good find

**Comment by amadeus** [comment]
Alright, I think the best way to get this tested, is going to be getting it into `master` and let the potential bug reports roll in. For the most part, I have been using this branch for about a week or so and not noticed anything. So hopefully it's just a couple small edgecases to solve, or hopefully it's perfect as is!

**Pull request merged**
