### PR TITLE
Added jsduck documentation types

### PR DESCRIPTION
**Pull request by juneidysoo**
e.g. @cfg {String} [name='test']
default value for name == 'test'

e.g. {@link doc.example.myclass#method-identify identify}
creates a link to class myclass' identify method

### CODE REVIEW

**Comment by qstrahl** [comment]
@juneidysoo You'll have to rebase to bring this PR up to date. Also, calling other maintainers for opinions on this change; seems harmless

**Comment by davidchambers** [comment]
I'm fine with this change.

**Comment by juneidysoo** [comment]
Updated :D

**Comment by davidchambers** [comment]
Thanks!

**Pull request merged**
