### PR TITLE
Update Master

### PR DESCRIPTION
**Pull request by amadeus**
It's been a few months since we last updated `master`, and there's a lot of really good things in `develop` that should definitely be going out soon.

### CODE REVIEW

**Comment by davidchambers** [comment]
:tada:

**Comment by amadeus** [comment]
One thing I still want to add is better argument destructuring support, so lets hold off on this until I can get something sorted for this.

**Comment by amadeus** [comment]
I also found a pretty big bug overall with how comments are handled, which should definitely get in for this release.

**Comment by amadeus** [comment]
Alright, this should be good. Any issues with getting this into `master`?

**Comment by davidchambers** [comment]
Great. Let's do it. :)

**Pull request merged**
