### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by amadeus**
Still some more work to be done, and I have some JSX improvements I'd like to get in here soon, but getting the PR started to kick us into gear to get these changes into `master`

### CODE REVIEW

**Comment by bounceme** [comment]
i have to work on the switch block indentation before a merge, hope to finish soon

**Comment by amadeus** [comment]
No worries, I want to re-look into some JS Flow stuff this weekend before we merge into `master`

**Comment by bounceme** [comment]
So i'm having some pretty serious bugs with the indentation, do you mind if i go back to the master version of the script? also any suggestions on the best way to revert, should I just make a new commit or try and revert?

**Comment by bounceme** [comment]
edited ^

**Comment by amadeus** [comment]
@bounceme what was the problem with the refactored indent script? It appeared to be working pretty well?

**Comment by bounceme** [comment]
i thought so also, then i tested with this file  http://pastebin.com/wrDcRTcd
also there are some strange inconsistencies with the performance technique i used to determine the type of pair to look for with the lookforparens function

**Comment by bounceme** [comment]
alright, looks like i fixed the refactored version potentially,a revert would be easy,and would restore the history(though i want to take better care to make sure we should before i do)

**Comment by bounceme** [comment]
i guess it is a matter of preference between current dev and https://github.com/pangloss/vim-javascript/pull/552 with some improvements. anyone have strong feelings on which we should use?

**Comment by amadeus** [comment]
@bounceme not sure I follow, using current `develop` #524 seems fixed?

**Comment by bounceme** [comment]
sorry, basically the version of the script here: https://github.com/pangloss/vim-javascript/blob/a7d5f9f83dcd2ab7da8e10cbba52713f8ff8f116/indent/javascript.vim (524 is fixed though there are a few bugs not related to that,which are fixable) and the newer,smaller,slower(in general) version that is in develop

**Comment by amadeus** [comment]
My thoughts thus far:

1. You say the new indent script is slower, yet based on this [comment](https://github.com/pangloss/vim-javascript/pull/515#issuecomment-230848418), it's comparable or even faster. Furthermore I have NOT noticed any performance hits in my day to day usage of it.
2. My assumption is this new version of the script is a lot easier to work with and smaller?

To me, both those points would qualify as a major win and definitely worth merging in.

You mentioned there may be a couple small issues, would you mind detailing them here or in a separate issue so we can be aware of them/have a log of them? Would those issues be fairly solvable in the future?

**Comment by bounceme** [comment]
edited

**Comment by bounceme** [comment]
we should probably just use the new version of the indentation

**Comment by bounceme** [comment]
also we can't easily support things like this since everything is based on offsets inferred by braces
```
  if()
    if()
      if()
        console.log("value");
```

**Comment by bounceme** [comment]
unrelated but, can we do something about the gq code in this pr?

**Comment by amadeus** [comment]
@bounceme regarding your first comment on the if statements, not sure what exactly you changed in that patch, but it does work rather nicely. However I haven't had time to test if there are other issues it may introduce?

In regards to `gq`, what kinds of changes would you like to address?

**Comment by bounceme** [comment]
so i think that also works in master, haven't checked though. About the gq stuff, maybe we can get some input from users about whether they'd like to have it included here or not.i think it should be removed

**Comment by amadeus** [comment]
Right now, it appears that `gq` just puts everything on the same line, essentially the sames as selecting a bunch of content and pressing `shift + j`.

If this is the case, `gq` should probably be removed

**Comment by bounceme** [comment]
indent script is ready! how is the jsx/flow work going @amadeus ?

**Comment by amadeus** [comment]
Alright, I think this is ready to go. @bounceme any last things you might want to do?

**Comment by bounceme** [comment]
Not really, this is ready

**Comment by amadeus** [comment]
@bounceme what about the PR you just opened? Should we wait for that?

**Comment by bounceme** [comment]
No ,its just a weird edge case
these issues are present currently:
```
if
()
fun()
```
and continuations within 'c-style' 
```
function ()
{
  var c = 1,
  o= r
}

**Comment by bounceme** [comment]
Maybe I could just merge it now though? only the first example is fixed, but having it tested by users be good

**Comment by amadeus** [comment]
@bounceme yeah that's good with me, go for it!

**Comment by bounceme** [comment]
you do the honors @amadeus !

**Comment by bounceme** [comment]
actually I have a possible fix for the 'c-style' issue

**Pull request merged**
