### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by amadeus**
Given we had some pretty big issues in `master` with the last release, I'd like us to get this merged in ASAP.

Although I'd like to at least get #394 and #392 merged in first.

I'd still like some more time to test the #391 before merging that in, so I say we still wait. Plus I am keeping it up to date with `develop` as we merge things in.

### CODE REVIEW

**Comment by amadeus** [comment]
Also I wonder if we should perhaps increment the version number, and perhaps create an official release tag with this. I think things are pretty solid once this gets merged in.

**Comment by bounceme** [comment]
would be fine with me,with all the changes we have this might be a good time,also lots of old issues have been fixed.

**Comment by amadeus** [comment]
Ok so all the major fixes have been merged in.

Do we want to include the performance improvements or not?

If not, I'll just add a tweak to the README to point out a new version and we can go ahead and merge this into `master`

**Comment by bounceme** [comment]
With the current performance I get I'm happy to just use the ones you already made yesterday.We can try and figure out some more using zs, vim regex is just kind of complicated. Otherwise merging sounds good

**Comment by amadeus** [comment]
Alright, I set the version number in the readme to 1.0.0

**Comment by eddiezane** [comment]
Spectacular work on this release @amadeus, @bounceme, @davidchambers, and others! Thanks so much for the effort.

**Comment by amadeus** [comment]
Aww shucks, thanks! 😄

**Pull request merged**
