### PR TITLE
feat(conceal): add arrow_function option

### PR DESCRIPTION
**Pull request by Delapouite**
Proper PR without extraneous commits

### CODE REVIEW

**Comment by okcompute** [comment]
It would be neat if this pull request gets merged. I modified my local copy and it works!

**Comment by davidchambers** [comment]
@amadeus, @qstrahl: Any objection to merging this?

**Comment by amadeus** [comment]
I am not too familiar with how to properly handle conceal stuff, so I think this is fine?

**Comment by okcompute** [comment]
Thank you! :)

**Pull request merged**
