### PR TITLE
changes according to #466

### PR DESCRIPTION
**Pull request by bounceme**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors#Dot_notation

### CODE REVIEW

**Comment by bounceme** [comment]
and an empty string is a valid property name? hah

**Comment by bounceme** [comment]
possibly adding basic computed properties also

**Comment by bounceme** [comment]
@amadeus is there a way to get a specific syntax group like jsblock but for objects only?

**Comment by amadeus** [comment]
@bounceme soooo, that's an update I am planning to do, and we will need it, especially for many ES6 features. Perhaps I can find some time tomorrow to look into it.

**Comment by bounceme** [comment]
thanks, all the new shorthand syntaxes are dependent on that, otherwise my giant regex matches basically every object literal property definition in es5

**Comment by bounceme** [comment]
i'll finish this with the es6/7 pr in mind. @amadeus i don't think the jsfuncargs group works across lines, is that something you would be able to fix?

**Comment by amadeus** [comment]
`jsFuncArgs` should work just fine over multiple lines. For example:

```js
var func = function(
    x,
    y
){
    return x + y;
};
```

If you are referring however to `jsArrowFuncArgs`, then yes, unfortunately this is a limitation I don't think we can get around.

The TL;DR is that `jsArrowFuncArgs` can only be matched by a test on the final `)` to detect a `=>`. The way vim handles `syntax regions`, it will just start the region regardless if it can find an ending match which means it would conflict with our `jsParens` region.

No other syntax file that I have found actually supports a multiline `jsArrowFuncArgs` like match, they all break the moment you create a new line within them.

**Comment by bounceme** [comment]
oh sorry, I mean is there an 'invoked function arguments' syntax pattern?

**Comment by amadeus** [comment]
@bounceme ahh, at this point no, although we could potentially chain something to the `jsFuncCall` logic if that would help? It could have some weird side effects tho.

**Comment by bounceme** [comment]
it isn't necessary really, jsparen is enough for now at least

**Comment by bounceme** [comment]
this pr was waiting on #466, a relatively minor update but the additions are helpful for objects handling

**Comment by bounceme** [comment]
going to merge this as it goes along with @amadeus 's update

**Pull request merged**
