### PR TITLE
Changed recommended foldmethod setting in README

### PR DESCRIPTION
**Pull request by cjbassi**
Just a small change, thought I would make the foldmethod setting specific to javascript.

### CODE REVIEW

**Comment by bounceme** [comment]
thanks, i dont think the autocmd part is necessary though. how about just change `set` to `setlocal` ?

**Comment by bounceme** [comment]
also:
```
'foldmethod' 'fdm'	string (default: "manual")
			local to window
```

does that mean it already is a local var?

**Comment by bounceme** [comment]
hard to interpret `h local-options`

**Comment by cjbassi** [comment]
After playing around with it a bit, it seems that `setlocal` sets the foldmethod for the current buffer, while `set` sets the foldmethod for the current buffer and all subsequently opened buffers. It would be better to do `setlocal` because for example you could open a javascript file and then a markdown file and the foldmethod setting gets carried over to the markdown file.

And then the `autocmd` part is so that `setlocal foldmethod=syntax` is called on every javascript file only and only when it's opened. So instead of putting `set foldmethod=syntax` in your vimrc where every while gets the setting, it's just javascript files.

**Comment by bounceme** [comment]
it's good to put autocmds as members of an augroup.

**Comment by cjbassi** [comment]
Oh yah you're right about the `au` group, I fixed that. Also true about the ftplugins folder. First time learning about that. At this point, I don't think it's that big of a deal how people implement the syntax folding, it probably won't cause any immediate issues, especially since you say in the README that it's a global option. Feel free to close this if you want.

**Pull request merged**
