### PR TITLE
Added more operator conceal

### PR DESCRIPTION
**Pull request by chinleung**
Allow the following conceal options:

```
let g:javascript_conceal_double_equal = "≈"
let g:javascript_conceal_triple_equal = "≡"
let g:javascript_conceal_or_operator = "∨"
let g:javascript_conceal_and_operator = "∧"
let g:javascript_conceal_not_operator = "¬"
let g:javascript_conceal_greater_equal_operator = "≥"
let g:javascript_conceal_less_equal_operator = "≤"
let g:javascript_conceal_not_equal_operator = "≠"
let g:javascript_conceal_not_strict_equal_operator = "≢"
```

### CODE REVIEW

**Comment by amadeus** [comment]
Can you add to the readme with these new changes so it's documented there?

**Comment by chinleung** [comment]
@amadeus I've added it below the other conceal options in the readme.

**Comment by amadeus** [comment]
Looks like there might need to be a rebase on this as well to fix conflicts

**Comment by chinleung** [comment]
@amadeus Is it okay now?

**Comment by provthomas** [comment]
is this happening?

**Comment by chinleung** [comment]
@amadeus What do you mean by how it was rebased? Can you please guide me on how to fix it properly? 

Thanks.

**Comment by provthomas** [comment]
> Can you please guide me on how to fix it properly?

Hi @chinleung and @amadeus I opened up a new PR that is this branch if it had been correctly based on master: https://github.com/pangloss/vim-javascript/pull/1140

@pangloss you could use the branch in my PR to fix this PR by running this command (assuming you don't have any local-only commits): 
`get fetch --all && git reset --hard 0cbd96e3aecba58fa33afebdc5154d6755a59275`

**Comment by pangloss** [comment]
@provthomas I don't think it's possible for me to what you ask. It'd have to be the done by @chinleung because it's his branch. Why not just merge the cherry-picked branch at #1140 and close this one?

**Comment by provthomas** [comment]
@pangloss oops! I meant to @chinleung instead of you in my second paragraph. Fine with merging #1140, but my disclaimer is that I know git and how to resolve merge conflicts _way_ better than I know vimscript, so please give it a good look-over before merging.

**Comment by amadeus** [comment]
Fixed in #1140

**Pull request closed without merging**
