### PR TITLE
Release 0.10

### PR DESCRIPTION
**Pull request by goatslacker**
Alright so let's merge this.

### CODE REVIEW

**Comment by goatslacker** [comment]
ping!

**Comment by davidchambers** [comment]
:ship:

**Comment by amadeus** [comment]
Sorry I didn't respond sooner. Been out of town this weekend, but I've been running this branch this entire month and haven't noticed any serious issues. I don't do any ES6 stuff, so I probably wouldn't be able to contribute anything there.

**Comment by davidchambers** [comment]
@goatslacker, did you mean to delete the `develop` branch?

**Comment by amadeus** [comment]
It doesn't seem to be deleted?

**Comment by davidchambers** [comment]
I just updated `develop` with the two extra commits on `master` (the merge commit for this PR and a README update). The two branches now have the same head.

**Comment by goatslacker** [comment]
Hah oops force of habit.

**Comment by goatslacker** [comment]
Thanks for restoring peace and order

**Pull request merged**
