### PR TITLE
Fix JSDoc highlighting for optional parameters

### LINKED ISSUE #574: JSDoc highlighting for optional parameters
I've noticed that `vim-javascript` does an excellent job with most JSDoc highlighting, but gets confused on [optional parameters](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values).

Here's a screenshot showing how both "normal" and "optional" parameters are handled.

screen shot 2016-07-26 at 1 29 54 pm

It would be great if it showed up the same color, and even better if the each part was highlighted separately to make the default value stand out, if provided.

### PR DESCRIPTION
**Pull request by tomxtobin**
Fixes #574.

### CODE REVIEW

**Comment by bounceme** [comment]
`\|\[.\{-}]` to this `\|\[.\{-}\]`

**Comment by tomxtobin** [comment]
> Does the closing bracket need to be escaped also?

Not with the default regex `magic`, no. (I find the magic rules so confusing that I always prefix my Vim regexes with `\v`, so they're fairly close to PCREs or POSIX EREs.)

**Comment by bounceme** [comment]
oh, in the help it explains the behavior that some internal functions have:
```

								*E769*
	When the ']' is not there Vim will not give an error message but
	assume no collection is used.  Useful to search for '['.  However, you
	do get E769 for internal searching.  And be aware that in a
	`:substitute` command the whole command becomes the pattern.  E.g.
	":s/[/x/" searches for "[/x" and replaces it with nothing.  It does
	not search for "[" and replaces it with "x"!
```

**Comment by bounceme** [comment]
Oh, that was into master haha. try not to do that

**Comment by amadeus** [comment]
Oh whoops, it was from mobile (so I couldn't see the target), and since it wasn't brought up earlier, I just assumed it was correct.

**Comment by bounceme** [comment]
I missed it too. the dev to master push should cover it up

**Pull request merged**
