### PR TITLE
laggy indent in object

### PR DESCRIPTION
**Pull request by bounceme**

### CODE REVIEW

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/issues/1174

this should fix it! thanks for the idea!

**Comment by amadeus** [comment]
Nice! While on the subject of this - should we also include `jsBracket` (for arrays), `jsDestructuringBraces` and `jsClassBlock`?

**Comment by amadeus** [comment]
Also, this definitely fixes the test case I created - however, it doesn't appear to fix the issue where I initially found it in a special file related to my work. I can't share that file - but it's a massive object with a lot of strings for translation. I'll do a quick profile and post here what seems to get lagged up in this particular case

**Comment by amadeus** [comment]
This gist is a profile I ran, at the bottom you can see what functions seem to get called a TON:

https://gist.github.com/amadeus/c5f518a008ee1824dbff2d86e4610a36

The syntax group I am in is `jsParen > jsObject `

**Comment by bounceme** [comment]
how are u generating these profiling logs? i havent vimscript'd in a long time now...
yea, there are many bottlenecks in giant list/objects. i have a few more of these to address with this pr.

**Comment by amadeus** [comment]
This is the vimscript I use to profile:

```
function! s:ProfileStart()
  profile start profile.log
  profile func *
  profile file *
endfunction

function! s:ProfileEnd()
  profile pause
  noautocmd qall!
endfunction

command! ProfileStart call s:ProfileStart()
command! ProfileEnd call s:ProfileEnd()
```

Basically I setup the situation (open the file move my cursor to the right location, then execute `:ProfileStart` then I perform the actions - then call `:ProfileEnd`. This stops the profile and creates a `profile.log` file in the current working directory of vim at the time of the profile.

**Pull request merged**
