### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by amadeus**
Some quick but important fixes from our last release.

@bounceme I assume you probably want to get an indent fix or two in here as well?

### CODE REVIEW

**Comment by bounceme** [comment]
yea, i'm going to need to test some more though

**Comment by bounceme** [comment]
if you are ready to merge you don't need to wait on my pr since I do think i'll need a day or two

**Comment by amadeus** [comment]
I'll wait for now, unless I see another issue regarding the issue that this fixes.

**Comment by bounceme** [comment]
tomorrow morning i'll merge my pr, after some more testing

**Comment by amadeus** [comment]
Ok, this has some fairly important fixes. Is this good to go?

**Comment by bounceme** [comment]
i think so.the last few commits are big improvements!

**Pull request merged**
