### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by amadeus**
Will need a version bump, me thinks.

### CODE REVIEW

**Comment by amadeus** [comment]
Also, I may need to rebase master back into develop, and fix some conflicts...

**Comment by amadeus** [comment]
So I can do the rebase, but it will require a force push to `develop`.

How do you all feel about this?

**Comment by bounceme** [comment]
I don't think thats a problem, i'm not too concerned with a perfect commit history

**Comment by amadeus** [comment]
The only issue I see is people who might be tracking develop right now, and use a plugin manager. If I do a force push, then those people will have their develop branches freak out.

**Comment by amadeus** [comment]
Another solution would be to still merge this in manually, but then create a new branch off of master to begin dev work on. But then that means people will stop getting updates on `develop`... Six of one, half a dozen of the other

**Comment by bounceme** [comment]
a rebase sounds cleaner, most people will want to be on master now anyway

**Pull request merged**
