### PR TITLE
Switch

### PR DESCRIPTION
**Pull request by bounceme**

### CODE REVIEW

**Comment by amadeus** [comment]
Right now when using a switch statement, with this branch or `develop`, indent is twice as much:

Desired:
```
switch (case) {
    case 2
}
```

Result
```
switch (case) {
        case 2
}
```

However, when I type the `:`, it goes back to the proper indent.

**Comment by bounceme** [comment]
the latest commit may fix that

**Comment by bounceme** [comment]
Is that fixed @amadeus ? i'll merge if so

**Comment by amadeus** [comment]
👌

**Comment by bounceme** [comment]
still working correctly?

**Comment by amadeus** [comment]
👌

**Pull request merged**
