### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by amadeus**
Just another base release. I kinda want to get this out soon though, so we stop getting those bug reports regarding the lookbehind limiters.

### CODE REVIEW

**Comment by davidchambers** [comment]
Let's do it. :)

**Comment by bounceme** [comment]
the indent script is ready for a merge

**Comment by amadeus** [comment]
i added a small issue I noticed in #443, is that an easy fix? If so, I'd like to get that in first, otherwise we can hold off and fix later.

**Comment by bounceme** [comment]
hmm, I'm at work. I'll try and fix it soon

**Comment by bounceme** [comment]
actually, since we use cindent for multiline comments, this is probably customizable. maybe in the cinoptions section of the vim help you can find it

**Comment by bounceme** [comment]
```
cN    Indent comment lines after the comment opener, when there is no
	      other text with which to align, N characters from the comment
	      opener.  (default 3).  See also |format-comments|.

		cino=			  cino=c5
		  /*			    /*
		     text.			 text.
		   */			     */
 ```

**Comment by amadeus** [comment]
Ok cool, then I think we can just go ahead and merge this, and I'll worry about that later.

**Comment by amadeus** [comment]
Alright, I think this may be good to go?

**Pull request merged**
