### PR TITLE
Flow updates

### PR DESCRIPTION
**Pull request by amadeus**
Misc fixes for the JS Flow plugin.

### CODE REVIEW

**Comment by gf3** [comment]
getting some leakage from `jsFlowTypeObject` after this last merge:

screen shot 2016-06-28 at 2 24 19 pm

**Comment by gf3** [comment]
if you add `;` to the end regex of `jsFlowTypeValue` it works as expected

**Comment by amadeus** [comment]
Can you create a new issue with a quick example broken snippet? I'll get on fixing these ASAP.

**Comment by gf3** [comment]
i'll open a PR in a couple mins

**Comment by amadeus** [comment]
@gf3 I do have a branch I am fixing a couple things in currently, so I may have already fixed this issue in that branch.

**Comment by gf3** [comment]
okay, issue created → https://github.com/pangloss/vim-javascript/issues/517

**Pull request merged**
