### PR TITLE
Add syntax highlight for jsDot, jsObjectColon

### PR DESCRIPTION
**Pull request by ajernej**
Hi,
this is my first pull request, so bare with me please if i made something wrong. thx.

vim

### CODE REVIEW

**Comment by amadeus** [comment]
I'm not opposed to this, and I'll need to do some further testing to ensure nothing breaks.

One thing right off though, you'll need to `HiLink` `jsDot` back into `jsNoise` or else it will break people's existing configurations.

**Comment by kirk1h** [comment]
thx for your reply. i have updated the file.

**Comment by amadeus** [comment]
Can  you rebase master into branch to resolve the conflicts and I can look into getting this merged shortly?

**Comment by amadeus** [comment]
Eek, looks like something didn't rebase right here

**Comment by kirk1h** [comment]
i am lost :(

**Comment by amadeus** [comment]
I think your best bet now is to:

* Checkout a backup branch from this branch - `git checkout -b backup`
* Get back on this master branch - `git checkout master`
* Reset your master back onto our master branch (I don't know what you list our origin as, so I can't give you the exact code snippet, but something like: `git reset pangloss/master --hard` (assuming our stuff is on `pangloss` origin
* Then cherry pick your 2 commits in order:
  * `git cherry-pick 38c84ab`
  * `git cherry-pick 0871a6f`
* Then force push `git push origin master --force`

**Comment by amadeus** [comment]
If for whatever reason you can get that to work, I'll setup a new PR where I cherry-pick your commits and merge from there.

**Comment by kirk1h** [comment]
Please do. This was my first fork and pull request and i screwed up badly. Sorry for that.

**Comment by amadeus** [comment]
I patched in your changes to master manually.

**Pull request closed without merging**
