### PR TITLE
adjustable indent (experimental)

### PR DESCRIPTION
**Pull request by bounceme**
https://github.com/mxw/vim-jsx/issues/116#issuecomment-244400990
thanks to @mxw for the suggestion, it is slightly less useful than the cindent version though

### CODE REVIEW

**Comment by bounceme** [comment]
@sassanh please test this out, ive made the changes you wanted

**Comment by bounceme** [comment]
here is a small demo
https://asciinema.org/a/3j66lltfis3p0mhhtgnycpz48

**Comment by sassanh** [comment]
@bounceme thank you, that was fast. It's alright overall though there are some minor issues. Look at this:
```
const a = <div
    a={1 +
            2 +
            3 +
            4 +
    }
    b={true
            ? 1
            : 2
    }
    c={true
            ? 1
            : 2 && (true &&
                    false &&
                    false &&
                    true) && (true &&
                            false &&
                            false &&
                            true) && (
                                true &&
                                    false &&
                                    true
                            )
    }>123
</div>;
```
While rest of expressions are reasonable and can be considered they're following a rule, last parenthesis is inconsistent.

**Comment by bounceme** [comment]
``` 
true) && (
                                true &&
                                    false &&
                                    true
                            )
```
that is because a continuation is started. the previous line ended in a parenthesis

**Comment by mxw** [comment]
What's a "continuation"?  Is it a JS construct I'm not aware of?

**Comment by bounceme** [comment]
not really, `:h cino-+`

**Comment by mxw** [comment]
I agree with @sassanh that

```
var foo = (
    true &&
        false &&
        false
);
```

is not a "correct" indentation—I don't know of any style guidelines (save perhaps the most bizarre Python styles) where this is recommended.  I think I empathize more with the difficulties of trying to maintain a cobbled-together pseudo-parser—but I don't think the implementation details are a good justification for behavior.

**Comment by mxw** [comment]
(I don't know the vim-javascript codebase at all, though, so for all I know this is prohibitively difficult to implement.)

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L83 is the extent of this 'pseudo parser' . I won't be removing line continuation, though you can with the config variables https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L63

**Comment by bounceme** [comment]
It could be changed to only happen in blocks(not in object literals, arrays, args), as with cindent

**Comment by sassanh** [comment]
This is another issue I found with this branch:
```
                <X
                    itemKey='id'
                    template={props =>
                            <QuestionTag {...props.item} readonly={true}/>}
                            callback={(event, _, __, items) => }
                />
```
`callback` should be indented as same level as `template`.

**Comment by bounceme** [comment]
are you sure that isn't an issue with jsx only?

**Comment by sassanh** [comment]
It happened after I checked out this branch, I'm sure it was working correctly in `develop` and `jsx` branches.

**Comment by bounceme** [comment]
as this is the javascript repo, could you please reduce this too a reproducible js only example?

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244528553
That is something I actually will do

**Comment by sassanh** [comment]
I just hope after you're done with it, it doesn't affect experience with `vim-jsx` if it doesn't improve it.

**Comment by sassanh** [comment]
Another issue:
```
if (true &&
    false) {
        const a = 1;
    }
```
last line should have indent width 0.

**Comment by bounceme** [comment]
thats unrelated, lines that start with `}])` are indented to the line which contains the other pair. wontfix

**Comment by sassanh** [comment]
I see, you're right, it happens in `develop` branch as well.

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244526767
is fixed

**Comment by sassanh** [comment]
Very nice, this latest commit made it much better. I continue testing and will share any problem I find here.

**Comment by sassanh** [comment]
A minor issue:
```
const a = true
    ? {
        zIndex: '1',
        backgroundColor: this.props.selected
        ? '#a0c4da'
        : '#cccccc',
        border: '1px solid #999999',
    }
    : {};
```
The ternary if in backgroundColor is not indented at all. Though I'm totally cool with its current indentation just thought it helps to report it.

**Comment by bounceme** [comment]
that contradicts https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244526767

**Comment by bounceme** [comment]
is that a github bug?^^

**Comment by sassanh** [comment]
I see, it's alright the way it is.

**Comment by bounceme** [comment]
I'll change it for objects if that is better

**Comment by sassanh** [comment]
We can try it.

**Comment by bounceme** [comment]
it makes no sense though, why not arrays? or parens?

**Comment by sassanh** [comment]
Yeah, array or parens/args will work.

**Comment by bounceme** [comment]
sure, https://github.com/pangloss/vim-javascript/blob/174d94e6f097851d495ba5cf0f8f537a9bcade62/indent/javascript.vim#L83 will work with those as well

**Comment by mxw** [comment]
> It could be changed to only happen in blocks(not in object literals, arrays, args), as with cindent

Yeah, that sounds like the right constraint to me.  Thanks for your work, @bounceme!  (Also thanks for jumping in on the `vim-jsx` thread earlier :] )

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244549552 I agree, and that's what we have now. thanks!

**Comment by bounceme** [comment]
Sorry, I'm confused now. I have local changes that make this behaviour:
```
var foo = (
        true &&
        false &&
        false
);
foo(
        true &&
                false &&
                false
);
```
is that better or worse?

**Comment by sassanh** [comment]
> is that better or worse?

I'd say it's definitly worse. Btw came here to thank you. It's just awesome now the way it is. There are some really minor issues that I even doubt are related to these commits. But overall it's just awesome.

**Comment by bounceme** [comment]
it fixes https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244531668 though. commas inside of arrays,objects,args still don't create indent

**Comment by sassanh** [comment]
https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244531668 is really minor imo comparing to https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244558129 which doesn't look good at all.

**Comment by bounceme** [comment]
got it, it is the same idea, it just looks strange with that example

**Comment by sassanh** [comment]
Currently your code snippet indents like this:
```
var foo = (
    true &&
    false &&
    false
);
foo(
    true &&
    false &&
    false
);
```
Which is exactly what I expect it. I which my C++ indenter would indent like this, I guess I should start a thread in their repo ð

**Comment by bounceme** [comment]
I don't know, but i'll be sticking to https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244528553

**Comment by bounceme** [comment]
do you think this is even necessary now ? https://github.com/pangloss/vim-javascript/blob/master/indent/javascript.vim#L63

**Comment by sassanh** [comment]
I don't know about that, I don't think so.

But look at this:
```
componentDidMount() {
        ::this.fetch();
}
```
double indent.

**Comment by bounceme** [comment]
fixed

**Comment by sassanh** [comment]
Didn't find any other issues with this branch. Checked it with ~2000 lines of js and jsx code.

**Comment by sassanh** [comment]
A really minor issue is it somehow tries to indent commented lines too :D 
```
                {/* <div style={styles.y}> */}
                    {/*     <Z */}
                        {/*         {...this.props.x} */}
                        {/*         readonly={true} */}
                        {/*     /> */}
                    {/* </div> */}
                {/* <div style={styles.y}> */}
                    {/*     <Z */}
                        {/*         {...this.props.x} */}
                        {/*         readonly={true} */}
                        {/*         resource='question-label' */}
```
But I guess it's not relevant to these commits.

**Comment by bounceme** [comment]
that is an issue with mxw/vim-jsx isn't it? i can't reproduce with ft=javascript

**Comment by bounceme** [comment]
since they are so prone to user error, and they aren't so needed now I'll add a deprecation warning in the readme

**Comment by sassanh** [comment]
I found an issue:
```
if (prevProps.x !==
    this.props.y) {
    this.setState({
        x: 1
    });
    }
```

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244529942

**Comment by sassanh** [comment]
Oh, right, my bad.

**Comment by sassanh** [comment]
What about this:
```
if (true &&
    false) {
    a({
        1: 2,
    });
        b = 1;
    }
```
`b=1` has wrong indentation.

**Comment by bounceme** [comment]
my results:
```
if (true &&
  false) {
    a({
      1: 2,
    });
    b = 1;
  }
```

**Comment by sassanh** [comment]
Yeah I got latest `develop` version and it's fixed.

**Comment by sassanh** [comment]
Are you using a variable to keep some state for indentation? After using it a while it will start indenting things like this https://github.com/pangloss/vim-javascript/pull/621#issuecomment-244587987 Like indenter didn't clean a variable or something like that.

**Comment by bounceme** [comment]
Yes, though it will never do things like that because it is used only in very specific circumstances. I did just fix something though which would cause some problems with the cache

**Comment by sassanh** [comment]
OK, I will tell you if I see it again.

**Comment by bounceme** [comment]
yea, only versions after https://github.com/pangloss/vim-javascript/commit/22d0e64ee15c906685cab631309e83882d692e38 had the problem

**Comment by sassanh** [comment]
Nice, it's much more stable after your latest commits. I can't even find minor issues. Good job.

**Comment by bounceme** [comment]
If there were any jsx bugs found here, you might report them at mxw/vim-jsx so they get recognized

**Comment by sassanh** [comment]
It happened again, in a vim session that was open for few hours, indentation went wrong. After restarting vim it worked alright.

**Comment by bounceme** [comment]
so what do i do with that information? the conditions absolutely prevent that from happening, my guess is jsx

**Comment by sassanh** [comment]
Yeah, I know that information is not helpful. Just though maybe it triggers something for you. I try to find out how to reproduce it.

**Comment by bounceme** [comment]
Well I have noticed jsx changing indent when repeatedly indenting

**Comment by sassanh** [comment]
Next time it happens I'll check a js file with `ft=javascript`. Then we can say for certain if it's related to `vim-javascript` at all or not. Last time it happened I was checking 3rd line of a js file (but with `ft=javascript.jsx`) the line it indented incorrectly wasn't in any JSXRegion. It was as simple as this:
```
import {x} from './y';
    import z from './w';
```

**Pull request merged**
