### PR TITLE
ternary experiment

### PR DESCRIPTION
**Pull request by bounceme**
very experimental, goal is better performance

### CODE REVIEW

**Comment by bounceme** [comment]
i've tested this locally, will merge later. much faster than the old method

**Comment by amadeus** [comment]
Any numbers on the improvements?

**Comment by bounceme** [comment]
kind of difficult to say, since the old version was split into different functions.

https://raw.githubusercontent.com/sanctuary-js/sanctuary-def/779fc342b04f5d74778ec628a0b9bb80b204c8e5/index.js

old: 4.12s

new: 3.9s

http://pastebin.com/raw/eQ4cDaKf

old: 0.5s

new: 0.45s

**Comment by bounceme** [comment]
there actually is some optimization left too

**Pull request merged**
