### PR TITLE
Add more entities in jsDomElemFuncs

### PR DESCRIPTION
**Pull request by AlexanderSkafte**
These should be here, right?

### CODE REVIEW

**Comment by ccarpita** [comment]
:+1:

**Comment by qstrahl** [comment]
Yes they should. Thanks!

**Comment by qstrahl** [comment]
Only one problem; please open this pull request against the `develop` branch; we like to test out changes for a while before exposing users to potential buggy behaviour.

**Comment by AlexanderSkafte** [comment]
@qstrahl Feel free to do it, I'm too lazy right now :)

**Pull request closed without merging**
