### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by bounceme**
I think it's a good idea to get this out. I forget about this stuff being dev only

edit: One or two more commits I want to get in this

### CODE REVIEW

**Comment by bounceme** [comment]
I'll fix the conflict and merge later today or tomorrow

**Comment by bounceme** [comment]
Can @amadeus or @BenoitZugmeyer  or @tomxtobin confirm whether i resolved the conflict correctly?

**Comment by bounceme** [comment]
I'm going to merge in an hour. Last chance syntax guys !

**Comment by BenoitZugmeyer** [comment]
You removed the line `HiLink jsForAwait             Keyword` I added in my PR. Was it on purpose? without this line, the `await` in `for await` expression isn't colored as a keyword.

screenshot_20161011_204759

**Comment by bounceme** [comment]
https://github.com/pangloss/vim-javascript/pull/653/commits/822dfe5f919a938682b4a0ad386f9d2909627e17 is the problem?

**Comment by BenoitZugmeyer** [comment]
It seems so, yes.

**Comment by tomxtobin** [comment]
I think my #660 is missing in there, as well?

**Comment by bounceme** [comment]
#660 is in master

**Comment by tomxtobin** [comment]
> #660 is in master

Whoops. Thanks!

**Comment by bounceme** [comment]
No conflicts now, how does this look @BenoitZugmeyer ?

**Comment by BenoitZugmeyer** [comment]
LGTM! thank you.

**Pull request merged**
