### PR TITLE
feat: add config for indenting chained method calls

### PR DESCRIPTION
**Pull request by gera2ld**
- add g:javascript_plugin_chain_indent
- See pangloss/vim-javascript#559

### CODE REVIEW

**Comment by bounceme** [comment]
thank you, there isn't really any point in merging this now since there may be large changes to the indent script soon. I think we should just make the `s:operator_first` and `s:continuation_regex` variables global

**Comment by bounceme** [comment]
will that be alright ? making the regexes global so it is completely configurable and we don't need global options for every operator (which I am against)

**Comment by gera2ld** [comment]
Sounds good. Do I need to update the PR or just close it?

**Comment by bounceme** [comment]
you can close it, I'll do this before we merge dev -> master

**Comment by bounceme** [comment]
#566

**Pull request closed without merging**
