### PR TITLE
Folds customization

### PR DESCRIPTION
**Pull request by zdm**
Following global variables added:

let g:javascript_fold_blocks = 1
let g:javascript_fold_comments = 1
let g:javascript_fold_functions = 1

### CODE REVIEW

**Comment by zdm** [comment]
This PR allows users to choose, what to fold: comments, functions, other code blocks.

**Comment by vokar** [comment]
Any possible progress regarding merging this PR?

**Comment by amadeus** [comment]
Unfortunately I am personally opposed to merging this - I don't really like converting a ton of syntax definitions to exec blocks, and we lose syntax highlighting.

**Comment by zdm** [comment]
I agree, that syntax is pretty ugly.
But is there is another way to fold functions only?

**Pull request closed without merging**
